### ISSUE TITLE
Example how to extract an entry from an archive

### ISSUE THREAD

**Issue by bapcyk** [shlok/archive-streaming#1]
Hi, would you add some short example, how to extract a file (as a stream) from the archive? I have a very big ZIP archive and I want to extract a file from it and parse it (it's JSON) on the fly, as a stream. Any example how to do something like this will be very helpful . I see just how to get a stream of either headers or ByteStrings but I have not idea what to do with it. Thanks!

**Comment by shlok** [comment]
Hey, I’m not really working on this repository anymore. I moved to the [streamly](https://hackage.haskell.org/package/streamly) library and created an [archive library](https://hackage.haskell.org/package/streamly-archive) for that one instead. There is an example there that might be useful in some ways. I guess you can use some JSON library such as [this one](https://hackage.haskell.org/package/json-stream) to achieve what you want.
